# AioSion Configuration

# AI Model Settings
ai_models:
  openai:
    default: gpt-3.5-turbo
    api_key: ${OPENAI_API_KEY}
  anthropic:
    default: claude-2
    api_key: ${ANTHROPIC_API_KEY}
  google:
    default: palm-2
    api_key: ${GOOGLE_AI_API_KEY}
  huggingface:
    default: gpt2
    api_key: ${HUGGINGFACE_API_KEY}
  local:
    default: llama-7b
    model_path: ${LOCAL_MODEL_PATH}

# Model Selection Strategy
model_selection:
  primary: openai
  fallback_order: [anthropic, google, huggingface, local]

# NLP Settings
nlp:
  model: en_core_web_sm
  max_length: 1000000
  batch_size: 1000
  enable_ner: true
  enable_sentiment_analysis: true
  summarization_ratio: 0.2

# Web App Settings
web:
  host: 0.0.0.0
  port: 8000

# Logging
logging:
  level: INFO
  file: logs/aiosion.log

# Feature Flags
features:
  use_cached_responses: true
  enable_voice_input: false
  enable_image_processing: false

# Performance
performance:
  max_concurrent_requests: 10
  request_timeout: 30  # seconds

# Security
security:
  enable_rate_limiting: true
  max_requests_per_minute: 60